"use strict";
const BREATHING_LANGUAGE_KEY="blood-measure-language";
const B={
  en:{dashboard:"Dashboard",meter:"Meter",pulse:"Pulse",eyebrow:"90-SECOND RECORDING",title:"Breathing-rate estimate",intro:"Estimate quiet breathing from slow modulation of the fingertip pulse signal.",ready:"Ready",instruction:"Sit quietly, breathe naturally, and keep your fingertip and phone still.",signalQuality:"Signal quality",start:"Start breathing estimate",stop:"Stop recording",recording:"Breathe naturally and remain completely still.",seconds:"{seconds} sec",resultTitle:"Experimental breathing-rate estimate",breathsMinute:"breaths/min",quality:"{quality}% analysis confidence · {channel} channel",warning:"This camera-derived estimate is sensitive to motion, finger pressure, and automatic exposure. It is not a respiratory diagnosis or emergency monitor.",history:"Breathing sessions",saved:"{count} saved",historyLine:"{rate} breaths/min · {quality}% confidence",cameraSecure:"Camera access requires HTTPS and permission.",cameraFailed:"The camera could not start.",notEnoughFrames:"Not enough camera frames. Try again.",tooShort:"The recording was too short. Try again.",exposure:"Adjust your fingertip to avoid poor exposure.",noBreathingSignal:"No respiratory modulation was detected.",lowBreathingQuality:"Breathing-signal confidence was too low. Keep still and try again.",cancelled:"Recording stopped."},
  zh:{dashboard:"仪表板",meter:"测量",pulse:"脉搏",eyebrow:"90 秒记录",title:"呼吸频率估计",intro:"根据指尖脉搏信号的缓慢调制估算安静呼吸频率。",ready:"准备就绪",instruction:"请安静坐好，自然呼吸，并保持指尖和手机静止。",signalQuality:"信号质量",start:"开始呼吸估计",stop:"停止记录",recording:"请自然呼吸并完全保持静止。",seconds:"{seconds} 秒",resultTitle:"实验性呼吸频率估计",breathsMinute:"次/分钟",quality:"分析置信度 {quality}% · {channel} 通道",warning:"此摄像头估计容易受到移动、手指压力和自动曝光影响，不用于呼吸系统诊断或紧急监测。",history:"呼吸记录",saved:"已保存 {count} 条",historyLine:"{rate} 次/分钟 · 置信度 {quality}%",cameraSecure:"摄像头访问需要 HTTPS 和授权。",cameraFailed:"无法启动摄像头。",notEnoughFrames:"摄像头帧数不足，请重试。",tooShort:"记录时间过短，请重试。",exposure:"请调整指尖以避免曝光不良。",noBreathingSignal:"未检测到呼吸调制信号。",lowBreathingQuality:"呼吸信号置信度过低，请保持静止后重试。",cancelled:"记录已停止。"}
};
let language=localStorage.getItem(BREATHING_LANGUAGE_KEY)||(navigator.language?.startsWith("zh")?"zh":"en"),recording=false;
const button=document.querySelector("#breathingButton"),instruction=document.querySelector("#instruction"),result=document.querySelector("#breathingResult"),countdown=document.querySelector("#countdown");
const recorder=window.FingertipRecorder.create({video:document.querySelector("#camera"),canvas:document.querySelector("#sampleCanvas"),onProgress:(progress,seconds)=>{countdown.textContent=t("seconds",{seconds});document.querySelector("#progress").style.boxShadow=`inset 0 0 0 ${progress*9}px #ec6376`;},onQuality:value=>{document.querySelector("#qualityBar").style.width=`${Math.round(value*100)}%`;document.querySelector("#qualityLabel").textContent=`${Math.round(value*100)}%`;}});
function t(key,values={}){let text=B[language][key]||key;Object.entries(values).forEach(([name,value])=>text=text.replaceAll(`{${name}}`,value));return text;}
function applyLanguage(){document.documentElement.lang=language==="zh"?"zh-CN":"en";document.querySelectorAll("[data-i18n]").forEach(element=>element.textContent=t(element.dataset.i18n));document.querySelector("#languageButton").textContent=language==="zh"?"English":"中文";renderHistory();}
document.querySelector("#languageButton").addEventListener("click",()=>{language=language==="en"?"zh":"en";localStorage.setItem(BREATHING_LANGUAGE_KEY,language);applyLanguage();});
button.addEventListener("click",async()=>{if(recording){recorder.cancel();return;}recording=true;button.textContent=t("stop");instruction.textContent=t("recording");result.hidden=true;try{const frames=await recorder.record(90);const reading=window.BloodMeasureRespiration.analyze(frames);const session={recordedAt:new Date().toISOString(),app:window.BLOOD_MEASURE_BUILD||null,...reading};window.BloodMeasureStore.record("respiratory-rate",session);showResult(session);renderHistory();instruction.textContent=t("ready");}catch(error){document.querySelector("#resultTitle").textContent=t(error.message==="cancelled"?"cancelled":error.message==="cameraSecure"?"cameraSecure":error.name==="NotAllowedError"?"cameraFailed":error.message);document.querySelector("#breathingRate").textContent="—";document.querySelector("#breathingQuality").textContent="";result.hidden=false;instruction.textContent=t("instruction");}finally{recording=false;button.textContent=t("start");countdown.textContent=t("ready");}});
function showResult(session){document.querySelector("#resultTitle").textContent=t("resultTitle");document.querySelector("#breathingRate").textContent=session.breathsPerMinute;document.querySelector("#breathingQuality").textContent=t("quality",{quality:Math.round(session.confidence*100),channel:session.channel});result.hidden=false;}
function renderHistory(){const sessions=window.BloodMeasureStore.getSessions().filter(item=>item.type==="respiratory-rate");document.querySelector("#breathingHistory").hidden=!sessions.length;document.querySelector("#historyCount").textContent=t("saved",{count:sessions.length});document.querySelector("#historyList").replaceChildren(...sessions.slice(0,8).map(item=>{const row=document.createElement("div");row.className="history-item";const strong=document.createElement("strong");strong.textContent=`${item.data.breathsPerMinute} ${t("breathsMinute")}`;const time=document.createElement("time");time.textContent=new Date(item.recordedAt).toLocaleString(language==="zh"?"zh-CN":undefined,{dateStyle:"medium",timeStyle:"short"});const detail=document.createElement("small");detail.textContent=t("historyLine",{rate:item.data.breathsPerMinute,quality:Math.round(item.data.confidence*100)});row.append(strong,time,detail);return row;}));}
window.addEventListener("pagehide",()=>recorder.cancel());applyLanguage();
