"use strict";
const RECOVERY_LANGUAGE_KEY = "blood-measure-language";
const R = {
  en: { dashboard:"Dashboard",meter:"Meter",pulse:"Pulse",eyebrow:"GUIDED TEST",title:"Pulse recovery",intro:"Compare your pulse immediately after activity and after one and two minutes.",prepareTitle:"Before starting",prepare:"Choose a safe, repeatable activity. Stop if you feel chest pain, faint, or unusually short of breath. This is a personal trend, not a fitness or heart diagnosis.",immediate:"Immediate",oneMinute:"1 minute",twoMinutes:"2 minutes",ready:"Ready",firstInstruction:"Complete your chosen activity, then begin the first recording immediately.",signalQuality:"Signal quality",recordImmediate:"Record immediate pulse",wait:"Next recording available in {seconds} seconds.",recordOne:"Record 1-minute pulse",recordTwo:"Record 2-minute pulse",recording:"Keep your fingertip still.",seconds:"{seconds} sec",resultTitle:"Pulse decrease from the immediate reading",immediatePulse:"Immediate pulse",oneMinuteDrop:"1-minute decrease",twoMinuteDrop:"2-minute decrease",warning:"Use this only to compare your own repeated sessions under similar conditions.",history:"Recovery sessions",saved:"{count} saved",historyLine:"1 min: {one} BPM · 2 min: {two} BPM",cameraSecure:"Camera access requires HTTPS and permission.",cameraFailed:"The camera could not start.",signalFailed:"A reliable pulse was not detected. Re-record this stage.",cancelled:"Recording cancelled."},
  zh: { dashboard:"仪表板",meter:"测量",pulse:"脉搏",eyebrow:"引导测试",title:"脉搏恢复",intro:"比较活动后即刻、1 分钟和 2 分钟时的脉搏。",prepareTitle:"开始之前",prepare:"请选择安全且可重复的活动。如出现胸痛、晕厥或异常呼吸困难，请立即停止。本功能仅用于个人趋势，不用于体能或心脏诊断。",immediate:"即刻",oneMinute:"1 分钟",twoMinutes:"2 分钟",ready:"准备就绪",firstInstruction:"完成所选活动后，请立即开始第一次记录。",signalQuality:"信号质量",recordImmediate:"记录即刻脉搏",wait:"距离下次记录还有 {seconds} 秒。",recordOne:"记录 1 分钟脉搏",recordTwo:"记录 2 分钟脉搏",recording:"请保持指尖静止。",seconds:"{seconds} 秒",resultTitle:"相对于即刻读数的脉搏下降值",immediatePulse:"即刻脉搏",oneMinuteDrop:"1 分钟下降",twoMinuteDrop:"2 分钟下降",warning:"仅用于在相似条件下比较您自己的重复测试。",history:"恢复测试记录",saved:"已保存 {count} 条",historyLine:"1 分钟：{one} BPM · 2 分钟：{two} BPM",cameraSecure:"摄像头访问需要 HTTPS 和授权。",cameraFailed:"无法启动摄像头。",signalFailed:"未检测到可靠脉搏，请重新记录此阶段。",cancelled:"记录已取消。"}
};
let language=localStorage.getItem(RECOVERY_LANGUAGE_KEY)||(navigator.language?.startsWith("zh")?"zh":"en"), stage=0, sessionStarted=null, readings=[] , timer=null, recording=false;
const button=document.querySelector("#recordButton"), instruction=document.querySelector("#instruction"), countdown=document.querySelector("#countdown"), qualityBar=document.querySelector("#qualityBar");
const recorder=window.FingertipRecorder.create({video:document.querySelector("#camera"),canvas:document.querySelector("#sampleCanvas"),onProgress:(progress,seconds)=>{countdown.textContent=t("seconds",{seconds});document.querySelector("#progress").style.boxShadow=`inset 0 0 0 ${progress*9}px #ec6376`;},onQuality:value=>{qualityBar.style.width=`${Math.round(value*100)}%`;document.querySelector("#qualityLabel").textContent=`${Math.round(value*100)}%`;}});
function t(key,values={}){let text=R[language][key]||key;Object.entries(values).forEach(([name,value])=>text=text.replaceAll(`{${name}}`,value));return text;}
function applyLanguage(){document.documentElement.lang=language==="zh"?"zh-CN":"en";document.querySelectorAll("[data-i18n]").forEach(element=>element.textContent=t(element.dataset.i18n));document.querySelector("#languageButton").textContent=language==="zh"?"English":"中文";updateStage();renderHistory();}
document.querySelector("#languageButton").addEventListener("click",()=>{language=language==="en"?"zh":"en";localStorage.setItem(RECOVERY_LANGUAGE_KEY,language);applyLanguage();});
button.addEventListener("click",async()=>{if(recording){recorder.cancel();return;}recording=true;button.textContent=t("cancelled");instruction.textContent=t("recording");try{if(stage===0)sessionStarted=Date.now();const frames=await recorder.record(15);const result=window.BloodMeasurePPG.analyze(frames);readings[stage]={targetSeconds:[0,60,120][stage],actualSeconds:Math.round((Date.now()-sessionStarted)/1000),bpm:Math.round(result.bpm),quality:result.quality};document.querySelector(`#step${stage}Value`).textContent=`${Math.round(result.bpm)} BPM`;stage++;if(stage===3)completeSession();else scheduleNext();}catch(error){instruction.textContent=t(error.message==="cancelled"?"cancelled":error.message==="cameraSecure"?"cameraSecure":error.name==="NotAllowedError"?"cameraFailed":"signalFailed");}finally{recording=false;countdown.textContent=t("ready");updateStage();}});
function scheduleNext(){clearInterval(timer);timer=setInterval(()=>{const remaining=Math.max(0,[0,60,120][stage]-Math.round((Date.now()-sessionStarted)/1000));button.disabled=remaining>0;instruction.textContent=remaining?t("wait",{seconds:remaining}):t(stage===1?"recordOne":"recordTwo");if(!remaining)clearInterval(timer);},250);}
function updateStage(){document.querySelectorAll("[data-step]").forEach((element,index)=>element.classList.toggle("active",index===stage));if(stage>=3){button.hidden=true;return;}button.hidden=false;button.textContent=t(stage===0?"recordImmediate":stage===1?"recordOne":"recordTwo");}
function completeSession(){clearInterval(timer);const session={recordedAt:new Date().toISOString(),app:window.BLOOD_MEASURE_BUILD||null,readings,oneMinuteDrop:readings[0].bpm-readings[1].bpm,twoMinuteDrop:readings[0].bpm-readings[2].bpm,method:"three-stage-camera-ppg-v1"};window.BloodMeasureStore.record("pulse-recovery",session);document.querySelector("#immediatePulse").textContent=readings[0].bpm;document.querySelector("#oneMinuteDrop").textContent=session.oneMinuteDrop;document.querySelector("#twoMinuteDrop").textContent=session.twoMinuteDrop;document.querySelector("#recoveryResult").hidden=false;instruction.textContent=t("ready");renderHistory();}
function renderHistory(){const sessions=window.BloodMeasureStore.getSessions().filter(item=>item.type==="pulse-recovery");document.querySelector("#recoveryHistory").hidden=!sessions.length;document.querySelector("#historyCount").textContent=t("saved",{count:sessions.length});document.querySelector("#historyList").replaceChildren(...sessions.slice(0,8).map(item=>{const row=document.createElement("div");row.className="history-item";const strong=document.createElement("strong");strong.textContent=`${item.data.readings[0].bpm} BPM`;const time=document.createElement("time");time.textContent=new Date(item.recordedAt).toLocaleString(language==="zh"?"zh-CN":undefined,{dateStyle:"medium",timeStyle:"short"});const detail=document.createElement("small");detail.textContent=t("historyLine",{one:item.data.oneMinuteDrop,two:item.data.twoMinuteDrop});row.append(strong,time,detail);return row;}));}
window.addEventListener("pagehide",()=>recorder.cancel());applyLanguage();
